# Generated by Django 5.0.6 on 2024-05-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_hobbies_name_hobbies_date_added_hobbies_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobbies',
            options={'verbose_name_plural': 'hobbies'},
        ),
    ]
