# Generated by Django 5.0.6 on 2024-05-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_hobbies_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hobbies',
            new_name='Hobby',
        ),
    ]
